Repository fga-eps-mds/2023.1-Dnit-Front, pull requests merged in 2023-06, with the labels that each got.

#24 23 campo uf
  src/App.css
  src/App.tsx
  src/components/Button.tsx
  src/components/Header.tsx
  src/components/form/FormularioCadastro.tsx
  src/components/form/Login.tsx
  src/components/form/Register.tsx
  src/consts/service.ts
  src/models/service.ts
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
  src/provider/Authentication.tsx
  src/service/cadastro.ts
  src/service/federativeUnit.ts
  src/service/login.ts
  src/service/register.ts
  src/service/unidadeFederativa.ts
  src/styles/App.css
  src/styles/form.css
Labels: bug

#25 22 Validação de email e senha
  src/components/form/Register.tsx
Labels: bug

#29 28 correcao validacao email
  src/components/form/Register.tsx
Labels: bug

#30 21 icone contraste
  src/App.css
  src/assets/icons/DNITicon.svg
  src/assets/icons/buttonContraste.png
  src/assets/icons/contrastButton.svg
  src/components/Header.tsx
Labels: bug

#32 31 Retirando validacao de email institucional
  src/components/form/Register.tsx
Labels: bug

#36 35 - Testes
  jest.config.js
  package.json
  src/components/form/Login.tsx
  src/components/form/Register.tsx
  src/tests/Cadastro.test.tsx
  src/tests/Login.spec.tsx
  src/tests/Register.spec.tsx
Labels: EPS, TEST

#38 37 ajustes tela esqueci senha
  src/App.tsx
  src/components/form/RecoverPassword.tsx
  src/pages/RecoverPassword.tsx
  src/service/recoverPW.ts
  src/service/register.ts
  src/tests/Recover.spec.tsx
  src/tests/Register.spec.tsx
Labels: HOTFIX

#19 #9 implementando de Tela Recuperar Senha
  src/App.tsx
  src/components/form/ResetPassword.tsx
  src/consts/service.ts
  src/models/service.ts
  src/pages/ResetPassword.tsx
  src/service/resetPassword.ts
  src/styles/form.css
  src/tests/Reset.spec.tsx
Labels: MDS, EPS, FEATURE

#46 45 hot fix tela de exclusao
  jest-report.xml
  package.json
  src/App.css
  src/App.tsx
  src/components/BreadCrumb.tsx
  src/components/Header.tsx
  src/components/components-escolasCadastradas/Dropdown.tsx
  src/components/components-escolasCadastradas/FiltragemTabela.tsx
  src/components/components-escolasCadastradas/Footer.tsx
  src/components/components-escolasCadastradas/Header.tsx
  src/components/components-escolasCadastradas/ModalBody.tsx
  src/components/components-escolasCadastradas/ModalExcluirEscolas.tsx
  src/components/components-escolasCadastradas/ModalExibirInformacoes.tsx
  src/components/components-escolasCadastradas/TabelaEscola.tsx
  src/components/components-escolasCadastradas/style/FiltragemTabela.css
  src/components/components-escolasCadastradas/style/Footer.css
  src/components/components-escolasCadastradas/style/Header.css
  src/components/components-escolasCadastradas/style/ModalExcluirEscolas.css
  src/components/components-escolasCadastradas/style/ModalExibirInformacoes.css
  src/components/components-escolasCadastradas/style/TabelaEscola.css
  src/components/form/Register.tsx
  src/consts/service.ts
  src/context/FiltroTabela.tsx
  src/context/Situation.tsx
  src/index.tsx
  src/models/service.ts
  src/pages/EscolasCadastradas.tsx
  src/pages/ExibirInformacoesEscola.tsx
  src/service/Situacao.ts
  src/service/changeSituation.ts
  src/service/deleteSituation.ts
  src/service/etapasDeEnsino.ts
  src/service/excluirEscola.ts
  src/service/listSchools.ts
  src/service/listarInfoEscola.ts
  src/service/municipio.ts
  src/styles/App.css
  src/styles/BreadCrumb.css
  src/tests/Excluir.spec.tsx
  src/tests/InfoEscola.spec.tsx
  src/tests/Login.spec.tsx
  src/tests/Register.spec.tsx
  src/tests/Situacao.spec.tsx
  src/tests/mock/service.ts
  src/tests/tabelaEscola.spec.tsx
  yarn.lock
Labels: MDS, HOTFIX
